[package]
name = "fdk-dataset-event-publisher"
version = "0.1.0"
edition = "2021"

[dependencies]
avro-rs = "0.13.0"
lapin = "2.1.1"
lazy_static = "1.4.0"
rdkafka = "0.28.0"
reqwest = "0.11.11"
schema_registry_converter = { version = "2.1.0", features = ["avro"] }
serde = { version = "1.0.137", features = ["derive"] }
serde_derive = "1.0.137"
serde_json = "1.0.81"
thiserror = "1.0.31"
tokio = { version = "1.19.2", features = ["full"] }
tokio-executor-trait = "2.1.0"
tokio-reactor-trait = "1.1.0"
tracing = "0.1"
tracing-subscriber = "0.2"
